services:
  postgres:
    image: "postgres:11-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U template" ]
      interval: 10s
      timeout: 5s
      retries: 3
